apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  spec:
    ports:
    - port: 31001
      nodePort: 31002
      targetPost: nodejs-port
      protocal: TCP
    selector:
      app: java-docker-microservice
    type: NodePort
